### ISSUE TITLE
Presence collection name

### ISSUE THREAD

**Issue by mquandalle** [3stack-software/meteor-presence#2]
I believe there is a accepted convention in the meteor community to name globals with upper-cased first letter. The `presences` collection doesn't respect this convention, I understand this is because you need to export the `Presence` symbol as a wrapper for the high-level API, but having both a `Presence` and `presences` is quite confusing.

Maybe this package could export a single symbol, `Presence`, and have the collection accessible via `Presence.collection` or something?

**Comment by nathan-muir** [comment]
Agreed. However I'll need to leave the lower-cased export for back-compat.

**Comment by mquandalle** [comment]
Yes — and yes, it's sad that meteor doesn't allow us to only `import` the symbols we want.

**Comment by derwaldgeist** [comment]
Personally, I'd prefer if the presences collection was tied to the Presence class as a static member. I do not really like if a package clutters the global namespace more than needed.
