### ISSUE TITLE
Presences document detele

### ISSUE THREAD

**Issue by aadamsx** [3stack-software/meteor-presence#5]
When I have a user come online, a document gets created, and is what I would have expected.  But when the user drops offline, the collection gets removed, which is not what I would have expected.  I would expect that the document that was created would stay and the status would go to offline or something like that.

**Comment by nathan-muir** [comment]
Hey @aadamsx 

Why did you want to keep the old sessions?

**Comment by aadamsx** [comment]
Well, because they may have just logged out, but then back in.  But anyhow I fixed this issue.  I'm keeping their 'online', 'idle', and 'offline' information in another collection and use this for displaying purposes.  The only thing that messing up now:

1) I'm using your idle-watcher along with this presence package

2) I'm using the presence package to sense when the user just closes a tab and puts them in the 'offline' state appropriately.

3) My problem is, when I have two different people (say a husband and wife) in two physically different locations (to different PCs) (completely different sessions), logged on as the same user.  idle-watcher tracker on each client just fight with each other and I get a circular reference loop going.

4) I tried to fix this by comparing the sessions and stopping one of the client's idle-watchers -- but I ran into issues where it would never come back online.

**Comment by nathan-muir** [comment]
Yep, so the situation that you describe in (3) is why presences work the way they do; 

Presences correspond with sessions, which have a _loose_ relationship to "identities" (users).

So, you need a bullet-proof way of mapping a Session, to the state of an "identity"... 

I would probably do something like this-


```js

// Pass the "idle" state for online users
Presences.configure({
  state(){
   return { idle: IdleWatcher.isIdle() };
  }
});


class PresenceMapper {
  constructor(collection){
    this.collection = collection;
    this.presenceByUserId = {};
    this.stateByUserId = new ReactiveDict(); 
    this.handle = this.watchPresences();
  }
  
  watchPresences(){
    var self = this;
    this.collection.find({}).observe({
      added(doc){
        self.addPresence(doc);
      },
      changed(doc, oldDoc){
        if (doc.userId !== oldDoc.userId){
          self.removePresence(oldDoc);
        }
        self.addPresence(doc);
      },
      removed(doc){
        self.removePresence(doc);
      }
    });
  }
  
  addPresence(presence){
    if (presence.userId != null){
      if (this.presenceByUserId[presence.userId] == null){
        this.presenceByUserId[presence.userId] = {};
      }
      this.presenceByUserId[presence.userId][presence._id] = presence;
      this.updateUserState(presence.userId)
    }
  }
  
  removePresence(presence){
    if (presence.userId != null){
      delete this.presenceByUserId[presence.userId][presence._id];
      this.updateUserState(presence.userId)
    }
  }
  
  updateUserState(userId){
    // get the list of presences for that user
    const presences = _.values(this.presenceByUserId[userId] || {});
    
    // If there are no presences, the user is offline
    if (presences.length === 0){
      this.stateByUserId.set(userId, 'offline');
    }
    
    // If every session is idle, then the user is idle
    if (_.every(presences, (p)=>p.idle)){
      this.stateByUserId.set(userId, 'idle');
    }
    
    // otherwise, the user is just "online"
    this.stateByUserId.set(userId, 'online');
  }
  
  getUserState(userId){
    const state = this.stateByUserId.get(userId);
    if (state != null){
      // XX - could try `.setDefault(userId, 'offline')` instead.
      return state;
    }
    return 'offline';
  }
}


const presenceMapper = new PresenceMapper(presences);

// use the presenceMapper.getUserState in a template helper or something
Template.myTemplate.helpers({
  userStatus(userId){  return presenceMapper.getUserState(userId); }
});
```

**Comment by aadamsx** [comment]
Thank you very much for this code, this will help I'm sure.  I'll see if I can incorporate it.
