### ISSUE TITLE
Which session am I?

### ISSUE THREAD

**Issue by aadamsx** [3stack-software/meteor-presence#6]
I have a situation (as we spoke about before), where I have two different people using the same userId.  

I found the presences collection has _id (this is connection.sessionKey and unique to the browser session), but from the client, I can't tell who I am because I don't have access to the sessionKey.  

I mean, I can publish the presences collection and filter by userId (and for example I'll have two records, one for each person).  And from one client I can see two different _id(s) (sessionKeys), but I don't know which one is "mine" from the client's point of view.

The question is, how can I tell which session in the presences collection belongs to a particular client (from the client) if I have two or more entires for a userId?

Note: In my case, the reason I want to know this is because I'm going to compare createdAt dates and which ever client came on first will get to keep it's IdleWatcher "on" while the others will not -- because I was having issues with the IdleWatchers on each client fighting with each other.

**Comment by nathan-muir** [comment]
Yeah, i get around this by not publishing the current sessions presence to the client.


eg,

```
Meteor.publish('everyoneElsesPresence', function(){
  return presences.find({_id: {$ne: this.connection.sessionKey}});
});
```

so, if there's a presence for the same user-id on the client, it must be from another browser session.
